### ISSUE TITLE
RangeError: "size" argument must not be larger than 2147483647

### ISSUE THREAD

**Issue by hktalent** [hktalent/webcrawler#1]
buffer.js:224
    throw err;
    ^

RangeError: "size" argument must not be larger than 2147483647
    at Function.Buffer.allocUnsafe (buffer.js:253:3)
    at Function.Buffer.concat (buffer.js:441:23)
    at Request.<anonymous> /webcrawler/node_modules/request/request.js:1133:30)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> webcrawler/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)

**Comment by hktalent** [comment]
vents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENFILE: file table overflow, open

**Comment by hktalent** [comment]
2019-05-23T17:45:30.176Z - error: CRAWLER Error Error: connect ENFILE  - Local (undefined:undefined) when fetching http:/// (3 retries left)
